apiVersion: 1
kind: datasource
metadata:
  name: prometheus-datasource
data:
  datasource:
    name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      httpMethod: POST
