apiVersion: 1
kind: alerting          # <-- Internal Grafana plugin expects 'alerting'
name: nuk-alerting-config
metadata:
  name: grafana-alerts
data:
  groups:
    - orgId: 1
      name: Default
      folder: ''
      interval: 1m
      rules: []
